### ISSUE TITLE
Suggestions from Discord

### ISSUE THREAD

**Issue by nitrofenix** [Natanaelel/TankStorage#1]
Keeping these in one place:

```
nitrofenix: i'd base it on banks but maybe with half the amount of slots per tier
trunksbomb: 8 buckets/16/64/256/1024/1000000
```

Tiers/capacities from the old mod (for reference/discussion only):
```
1: 3 tanks of 4000 mB each
2: 6 tanks of 16000 mB each
3: 9 tanks of 64000 mB each
4: 12 tanks of 256000 mB each
5: 15 tanks of 1024000 mB each
6: 18 tanks of 4096000 mB each
7: 27 tanks of 247483647 mB each
```

**Comment by trunksbomb** [comment]
Huh, would you look at that - I was pretty spot on for capacity :)

Additional suggestions:
* Lockable slots
* Automatic pickup of fluids when standing in them? Probably not a good idea
* use the tank itself as the bucket (no dedicated bucket item like entangled buckets)
* shift + click air to change modes, shift + scroll while in "build" mode to change which liquid you're selecting
* definitely a "void" mode to void excess fluids
* maybe a sponge mode, or a mode that functions like a hose pulley from Create so you can target one block of fluid and have it suck up other blocks in the same body of water
* shift+click bucket of fluid in inventory while Tank GUI is open automatically inserts the fluid from that bucket, like Modern Industrialization machines

**Comment by Natanaelel** [comment]
Done so far:
- tank 1-7 and dock
- can interact with buckets/similar in gui including shift click
- can interact with pipes in world using dock
- can lock slots

**Comment by nitrofenix** [comment]
Heck yes, might give it a test run if I get some time over the next day or so

**Comment by Natanaelel** [comment]
It's ready for testing! Recipes and number rendering is left to do. jar can be grabbed [here](https://github.com/Natanaelel/TankStorage/actions/runs/9392042940)
I am also thinking about reducing the number of slots per tier but upping the capacity. I think most slots will be unused unlike banks. And in vanilla there are only 2 fluids.
