### ISSUE TITLE
Number format

### ISSUE THREAD

**Issue by Natanaelel** [Natanaelel/TankStorage#2]
Here I collected how multiple different mods display fluid count.
This formatted number will be used in the fluid slots in the tank gui and in tooltips. It is important that the resulting string will fit into the slot.
Choices to make:
unit (mB, B, L, none)
eh just give your opinion this is getting too formal
|    droplets |  ae2 |         mi |     emi |      jade |    wthit | tank? |
| ----------: | ---: | ---------: | ------: | --------: | -------: | ----: |
|           1 |   ~0 |     0 ¹⁄₈₁ |         |  0 ¹⁄₈₁mB |     0 mb |     x |
|          80 |   ~0 |    0 ⁸⁰⁄₈₁ |         | 0 ⁸⁰⁄₈₁mB |     0 mB |     x |
|          81 | .001 |          1 |     1 L |       1mB |     1 mB |     x |
|         810 |  .01 |         10 |    10 L |      10mB |    10 mB |     x |
|        8100 |   .1 |        100 |   100 L |     100mB |   100 mB |     x |
|       18000 | .222 |  222 ¹⁸⁄₈₁ |   222 L | 222 ²⁄₉mB |   222 mB |     x |
|       81000 |    1 |       1000 |  1000 L |        1B |    1K mB |     x |
|       81081 |   ~1 |       1001 |  1001 L |        1B |    1K mB |     x |
|       81810 | 1.01 |       1010 |  1010 L |        1B | 1.01K mB |     x |
|       81891 | 1.01 |       1011 |  1011 L |        1B | 1.01K mB |     x |
|      810000 |   10 |      10000 | 10000 L |       10B |   10K mB |     x |
|      810081 |  ~10 |      10001 | 10001 L |       10B |   10K mB |     x |
|      810810 |  ~10 |      10010 | 10010 L |       10B |   10K mB |     x |
|      850500 | 10.5 |      10500 | 10500 L |       10B | 10.5K mB |     x |
|     8100000 |  100 |     100000 |         |      100B |  100K mB |     x |
|     8140500 | ~100 |     100500 |         |      100B |  101K mB |     x |
|     8140500 | ~100 |     100500 |         |      100B |  101K mB |     x |
|    81000000 | 1000 |    1000000 |         |       1kB |    1M mB |     x |
|    81040500 | 1000 |    1000500 |         |       1kB |    1M mB |     x |
|    81081000 | 1001 |    1001000 |         |       1kB |    1M mB |     x |
|    81810000 | 1010 |    1010000 |         |    1.01kB | 1.01M mB |     x |
|   810000000 |  10K |   10000000 |         |      10kB |   10M mB |     x |
|   818100000 |  10K |   10100000 |         |    10.1kB | 10.1M mB |     x |
|  8100000000 | 100K |  100000000 |         |     100kB |  100M mB |     x |
| 81000000000 | 1.0M | 1000000000 |         |       1MB |    1G mB |     x |

**Comment by nitrofenix** [comment]
Kinda think I like the EMI format, using L..?

**Comment by Natanaelel** [comment]
solved: unit makes the text too long
