### ISSUE TITLE
1.21.1 Update

### ISSUE THREAD

**Issue by penturt** [Natanaelel/TankStorage#4]
Could you please update to 1.21.1 NeoForge?

**Comment by Natanaelel** [comment]
Have you tried the 1.21 version? It should work.

**Comment by penturt** [comment]
So yes if I download and drop into mods it works, but if I want to install it via a mod launcher like curse forge or GD Launcher it doesn't come up as a compatible 1.21.1 mod, so it makes it hard for when creating a mod pack. Maybe it just needs to be marked as 1.21.1 compatible?

**Comment by Natanaelel** [comment]
Yes, done.
