### ISSUE TITLE
Fluid rendering crash when locking empty slot

### ISSUE THREAD

**Issue by Linguardium** [Natanaelel/TankStorage#5]
**Mod version**
1.0.2

**Describe the bug**
game attempts to render invalid fluid if empty slot is locked

**To Reproduce**

Lock empty slot
hover over item to cause tooltip rendering

**Expected behavior**
empty slots (even locked ones) should be filtered out from rendering

**Screenshots**

**Logs**
latest: https://mclo.gs/HzxEywv
crash: https://mclo.gs/M9u59s9

**Additional context**

**Comment by Natanaelel** [comment]
Fixed in 1.0.3
