### ISSUE TITLE
Tank Link Won't Craft

### ISSUE THREAD

**Issue by PinkScreamingUnicorn** [Natanaelel/TankStorage#6]
**Mod version**
1.0.3+1.21.jar
In the Craftoria modpack on CurseForge

**Describe the bug**
The Tank Link will not craft. There is no output in a crafting table. 

**To Reproduce**
1. Try to craft by placing items in their respective spots in a crafting grid.
2. Fail at crafting, as nothing will appear.

**Expected behavior**
The Tank Link crafts. 

**Screenshots**
No screenshot needed, it looks exactly as you would expect it to. 

**Logs**
N/A, I believe. 

**Additional context**
Nothing extra, just the little bug.

**Comment by Natanaelel** [comment]
The tank must be opened once to initialize it.

**Comment by PinkScreamingUnicorn** [comment]
🙏 Thank you, worked like a charm. Didn't expect to need to do that
since all the other recipes were fine without needing to open the banks
first.
